### ISSUE TITLE
no add() function

### ISSUE THREAD

**Issue by sugin223pl** [MeiKatz/php-event-stream#1]
$stream->add( $b ); 
Fatal error: Uncaught Error: Call to undefined method EventStream::add() in ....php:28

**Comment by MeiKatz** [comment]
@sugin223pl It's been six years since I created this repository and updated it last. And never before anybody used it and therefore nobody noticed, that this method is missing :laughing: . I will add it in and refactor the code. My skills have improved in the last six years :wink:

**Comment by MeiKatz** [comment]
Fixed it.
